using System;
using System.Collections.Generic;

namespace BDSMDiscordBot.Models
{
    /// <summary>
    /// A message within a text channel.
    /// <seealso cref="https://discord.com/developers/docs/resources/channel#message-object"/>
    /// </summary>
    public class ChannelMessage : Identifiable
    {
        /// <summary>
        /// Gets or sets the id of the message.
        /// </summary>
        public string? Id { get; set; }

        /// <summary>
        /// Gets or sets the type of message.
        /// </summary>
        public ChannelMessageType Type { get; set; }

        /// <summary>
        /// Gets or sets the the author of this message (not guaranteed to be a valid user, see below).
        /// </summary>
        /// <remarks>
        /// The author object follows the structure of the user object, but is only a valid user in the case where the
        /// message is generated by a user or bot user. If the message is generated by a webhook, the author object
        /// corresponds to the webhook's id, username, and avatar. You can tell if a message is generated by a
        /// webhook by checking for the <code>webhook_id</code> on the message object.
        /// </remarks>
        public DiscordUser? Author { get; set; }

        /// <summary>
        /// Gets or sets the when this message was sent.
        /// </summary>
        public DateTimeOffset? Timestamp { get; set; }

        /// <summary>
        /// Gets or sets the when this message was edited (or null if never).
        /// </summary>
        public DateTimeOffset? EditedTimestamp { get; set; }

        /// <summary>
        /// Gets or sets the 
        /// </summary>
        public DateTimeOffset? CallEndedTimestamp { get; set; }

        /// <summary>
        /// Gets or sets the whether this message is pinned.
        /// </summary>
        public bool IsPinned { get; set; }

        /// <summary>
        /// Gets or sets the contents of the message.
        /// </summary>
        public string? Content { get; set; }

        /// <summary>
        /// Gets or sets any attached files.
        /// </summary>
        public IReadOnlyList<ChannelAttachment> Attachments { get; set; } = new List<ChannelAttachment>().AsReadOnly();

        /// <summary>
        /// Gets or sets any embedded content.
        /// </summary>
        public IReadOnlyList<ChannelEmbed> Embeds { get; set; } = new List<ChannelEmbed>().AsReadOnly();

        /// <summary>
        /// Gets or sets any reactions to the message.
        /// </summary>
        public IReadOnlyList<ChannelReaction> Reactions { get; set; } = new List<ChannelReaction>().AsReadOnly();

        /// <summary>
        /// Gets or sets the users specifically mentioned in the message.
        /// </summary>
        public IReadOnlyList<DiscordUser> MentionedUsers { get; set; } = new List<DiscordUser>().AsReadOnly();
    }
}
